name: Update Version from Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  update-version:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tag
      id: get_version
      run: |
        $tag = "${{ github.ref_name }}"
        $version = $tag -replace '^v', ''
        Write-Output "VERSION=$version" >> $env:GITHUB_OUTPUT
        Write-Output "Tag: $tag, Version: $version"
      shell: pwsh

    - name: Update csproj version
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        $content = Get-Content "LolManager.csproj"
        $content = $content -replace '<AssemblyVersion>.*</AssemblyVersion>', "<AssemblyVersion>$version.0</AssemblyVersion>"
        $content = $content -replace '<FileVersion>.*</FileVersion>', "<FileVersion>$version.0</FileVersion>"
        $content = $content -replace '<Version>.*</Version>', "<Version>$version</Version>"
        Set-Content "LolManager.csproj" $content
        Write-Output "Updated version to $version"
      shell: pwsh

    - name: Commit version changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add LolManager.csproj
        git commit -m "Update version to ${{ steps.get_version.outputs.VERSION }}"
        git push origin HEAD:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}